### PR TITLE
use prebuild lights.mt6797

### PR DESCRIPTION
**Pull request by Verevka**
some changes to build with mod framework_av (thanks DeckerSU)

### CODE REVIEW

**Comment by DerTeufel** [comment]
Thanks for your efforts, but why should we merge this and the other commit? 
Our liblights are way better than stock, and ril is also working fine.

**Comment by DerTeufel** [comment]
libnetutils also is not needed

**Comment by fire855** [comment]
You are seriously adding prebuilt libnetutils from 6.0? Oh man..
I created a completely new and MUCH better lights hw hal for apollo. The stock one is just bullshit. Who is using prebuilt libraries when you can build them also from source...

**Comment by Verevka** [comment]
Sorry, I'm just learning =)

**Comment by dragonpt** [comment]
This commit looks good...

**Comment by dragonpt** [comment]
...Nope it's shit, sorry ....
.... Too drunk

**Comment by dragonpt** [comment]
Looking again...

**Comment by dragonpt** [comment]
Nope , still shit

**Pull request closed without merging**
